primitive(d3.select("#aweRect"))
  .json({"fill" : "blue", "r": 100 ,"cx":0,"cy":0})
  .properties({"margins": {"top": 10, "bottom" : 10}})
  .data("hello Fred")
  .element("circle")
  .updateNode()
  .updateJson()
  .transition()
  .json({"fill" : "red", "r": 50, "cx":50,"cy":100}).duration(4000).spark()
  .spread().json({"fill" : "green", "r": 100, "cx":50,"cy":100}).duration(4000).spark()
  .release()
